### PR TITLE
Updated demo.

### LINKED ISSUE #30: Update demo to match published labels.
Published labels have changed (#24, #27) since the demo was written. cc @balajismaniam

### PR DESCRIPTION
**Pull request by balajismaniam**
Fixes #30. 
- Updated pod templates with new label prefix.
- Minor changes to job scripts and readme.

### CODE REVIEW

**Comment by balajismaniam** [comment]
We can wait on this till there is a resolution for #27.

**Comment by ConnorDoyle** [comment]
@balajismaniam is this ok to review?

**Comment by balajismaniam** [comment]
@ConnorDoyle Updated. PTAL.

**Pull request merged**
