### PR TITLE
Fix to report the correct version inside container.

### PR DESCRIPTION
**Pull request by balajismaniam**
Fixes https://github.com/kubernetes-incubator/node-feature-discovery/issues/54. Tested manually.
- Removed demo directory from .dockerignore.

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Not opposed to this fix, but we could also consider injecting the version instead of trying to compute it inside the container? We could look at using `--build-arg` in the makefile (https://docs.docker.com/engine/reference/commandline/build/#/set-build-time-variables---build-arg)

**Comment by balajismaniam** [comment]
@ConnorDoyle I updated it. PTAL. See output below. 
```sh
root@e6ca80a74e13:/go/src/github.com/kubernetes-incubator/node-feature-discovery# git status
On branch fix-nfd-version-suffix
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    demo/README.md
        deleted:    demo/docker-images/Dockerfile-CloverLeaf
        deleted:    demo/docker-images/Dockerfile-PARSEC
        deleted:    demo/docs/performance-comparison-cloverleaf-norm.png
        deleted:    demo/docs/performance-comparison-parsec-norm.png
        deleted:    demo/helper-scripts/aggregate-logs-and-plot.sh
        deleted:    demo/helper-scripts/box-plot-norm.R
        deleted:    demo/helper-scripts/box-plot.R
        deleted:    demo/helper-scripts/clean-up.sh
        deleted:    demo/helper-scripts/demo-pod-with-discovery.json.parsec.template
        deleted:    demo/helper-scripts/demo-pod-with-discovery.yaml.cloverleaf.template
        deleted:    demo/helper-scripts/demo-pod-without-discovery.json.template
        deleted:    demo/helper-scripts/run-with-discovery.sh
        deleted:    demo/helper-scripts/run-without-discovery.sh

no changes added to commit (use "git add" and/or "git commit -a")
root@e6ca80a74e13:/go/src/github.com/kubernetes-incubator/node-feature-discovery# /go/bin/node-feature-discovery --version
node-feature-discovery cc335e6
root@e6ca80a74e13:/go/src/github.com/kubernetes-incubator/node-feature-discovery# git describe --tags --dirty --always
cc335e6-dirty
```

**Comment by ConnorDoyle** [comment]
Nice.

**Pull request merged**
