### PR TITLE
README: add a kubernetes incubator section

### PR DESCRIPTION
**Pull request by philips**

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
👍 LGTM, but want to merge #3 first to avoid rebasing again.

**Comment by philips** [comment]
@ConnorDoyle Cool, sounds good. LMK if I need a rebase!

**Comment by ConnorDoyle** [comment]
Also created our first issue to track graduation criteria here: https://github.com/kubernetes-incubator/node-feature-discovery/issues/4

**Comment by ConnorDoyle** [comment]
@philips rebase please

**Pull request closed without merging**
