### PR TITLE
Fix json syntax errors in the node-discovery template

### PR DESCRIPTION
**Pull request by chaitanyaenr**

### CODE REVIEW

**Comment by marquiz** [comment]
Those values are placeholders that are supposed to be replaced with numbers so I think this PR is invalid.

**Comment by okartau** [comment]
this change actually breaks label-nodes.sh as replaced string in quotes becomes different data type:

./label-nodes.sh
error: error validating "node-feature-discovery-job.json": error validating data: [ValidationError(Job.spec.completions): invalid type for io.k8s.api.batch.v1.JobSpec.completions: got "string", expected "integer"

**Comment by chaitanyaenr** [comment]
makes sense, closing the PR.

**Pull request closed without merging**
