### PR TITLE
Update the container image tags in the templates to v0.2.0

### PR DESCRIPTION
**Pull request by marquiz**
Issue #123

### CODE REVIEW

**Comment by SteffenSeckler** [comment]
you might also want to update the other job template. (deamon)

**Comment by marquiz** [comment]
> you might also want to update the other job template. (deamon)

Umm, that is updated in the patch, isn't it(?)

**Comment by SteffenSeckler** [comment]
ah yes, I'm just blind. Sorry for that.

**Comment by balajismaniam** [comment]
@marquiz can you please update this branch? I just want to make sure it passes with the current master.

**Comment by marquiz** [comment]
> can you please update this branch?

@balajismaniam: done

**Comment by balajismaniam** [comment]
LGTM.
@marquiz merge whenever you are ready.

**Pull request merged**
