### PR TITLE
Migrate from glide to godep

### PR DESCRIPTION
**Pull request by andyxning**
This PR is part of #74 .

This PR keep node-feature-discovery skeleton in sync with [kubernetes-template-project](https://github.com/kubernetes/kubernetes-template-project).

Note: This PR also migrate vendor management tool from glide to godep.

This PR should be accepted after #75 .
/cc @ConnorDoyle @balajismaniam

### CODE REVIEW

**Comment by balajismaniam** [comment]
@andyxning For graduating to beta, I don't think it is necessary to move from glide to godep. Closing this PR for now.

**Comment by andyxning** [comment]
Make node-feature-discovery's skeleton suitable for an kubernetes repo should be done ASAP, imo.

WDYT @dchen1107 @balajismaniam

**Comment by ConnorDoyle** [comment]
I think @balajismaniam's point is that the template project is not prescriptive at all about go dependency manager tooling, and therefore isn't relevant to beta graduation.

**Comment by andyxning** [comment]
@ConnorDoyle 

That was my mistake. I mixed two logical different commits into one. The reason for doing this is that as stated in the template project `godep` is suggested(maybe it is not a strong restrict because moving to glide has actually been discussed in Kubernetes.).

**Pull request closed without merging**
