### PR TITLE
Add kad to OWNERS file

### PR DESCRIPTION
**Pull request by kad**
As backup reviewer/approver if other project members are away.

### CODE REVIEW

**Comment by poussa** [comment]
+1

**Comment by marquiz** [comment]
:+1:

**Comment by balajismaniam** [comment]
A reference for adding owners in the Kubernetes community: https://github.com/kubernetes/community/blob/master/community-membership.md#approver. At this point, we should wait before merging this as it will give @kad time to grow into an ownership role for this repo.

**Comment by balajismaniam** [comment]
Closing this for now. Reopen when @kad is ready to be added as a owner.

**Pull request closed without merging**
