### PR TITLE
Implement nfdadm

### PR DESCRIPTION
**Pull request by marquiz**
Implement a helper tool for deploying NFD (see issue #125). The script is currently cabable of deploying NFD as a DaemonSet or Job, configuring RBAC, creating target namespace and also undeploying NFD.

### CODE REVIEW

**Comment by balajismaniam** [comment]
@marquiz At a high-level, I'm not sure if this PR is required. NFD is deployed as a simple daemonset or a run to completion job. While this kind of a tool might be required for a complicated installation for Kubernetes (e.g., kubeadm), NFD can be deployed with a much more simple script or `kubectl create -f`.

**Comment by marquiz** [comment]
I find it useful as it automatically configures (and deconfigures) RBAC, sets up a namespace and provides an easy way to customize probably the most commonly used settings (like image name). But, it's true that NFD is a simple service and this might be an overkill. It'd be nice to get some comments from others, as well – whether or not this would be something useful and make NFD more approachable.

**Comment by balajismaniam** [comment]
Ok. Still my opinion is that this tool is unnecessary. We can think about helm charts. However, even that might not be required for such a simple project and deployment.

**Comment by balajismaniam** [comment]
Closing this. If there is a necessity, we can use helm charts.

**Pull request closed without merging**
